# Book settings

title: A Digital Twin Components for Glaciers  # The title of the book. Will be placed in the left navbar.
author: DTC-Glaciers consortium  # The author of the book
copyright: "2024-2025"  # Copyright year to be placed in the footer
logo: img/ESA_logo.svg  # A path to the book logo
repository:
  url: https://github.com/DTC-Glaciers/dtc-glaciers.github.io
  path_to_book: .
  branch: stable
html:
  favicon: img/favicon.png
  analytics:
    plausible_analytics_domain: dtcglaciers.org
    plausible_analytics_url: https://plausible.oggm.org/js/script.js
  # use_repository_button: true
  # use_issues_button: true
  # use_edit_page_button: true
  # extra_css:
  #   - _static/custom.css
  extra_footer: |
    <p>
    &copy; Copyright 2024-2025. These materials are licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY license</a>.
    </p>
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: '%b %d, %Y'
execute:
  execute_notebooks: auto  # off (for tests)
  timeout: -1
  allow_errors: true
exclude_patterns: [.virtual_documents/*,README.md,sandbox/*,ignore/*,ioggm*]
sphinx:
  config:
    templates_path: ["_templates"]
    html_theme: pydata_sphinx_theme
    html_sidebars:  # Removes the sidebar for the index page
      index: []
    html_show_copyright: false
    html_theme_options:
      secondary_sidebar_items: []
      navbar_persistent: []
      footer_start: ["license"]
      footer_center: []
      footer_end: ["author"]
      icon_links:
        - name: GitHub,
          url: https://github.com/DTC-Glaciers
          icon: "fa-brands fa-github"
          type: fontawesome
