# Book settings

title: A Digital Twin Components for Glaciers  # The title of the book. Will be placed in the left navbar.
author: DTC-Glaciers consortium  # The author of the book
copyright: "2024-2025"  # Copyright year to be placed in the footer
logo: img/ESA_logo.svg  # A path to the book logo
repository:
  url: https://github.com/DTC-Glaciers/dtc-glaciers.github.io
  path_to_book: .
  branch: stable
html:
  favicon: img/favicon.png
  extra_css:
    - _static/custom.css
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - deflist
    - colon_fence
    # - amsmath
    # - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    # - substitution
    # - tasklist
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: '%b %d, %Y'
execute:
  execute_notebooks: auto  # off (for tests)
  timeout: -1
  allow_errors: true
exclude_patterns: [.virtual_documents/*,README.md,sandbox/*,ignore/*,ioggm*]
sphinx:
  config:
    templates_path: ["_templates"]
    html_theme: pydata_sphinx_theme
    html_sidebars:  # Removes the sidebar for the index page
      index: []
      team: []
      privacy: []
    html_show_copyright: false
    html_theme_options:
      secondary_sidebar_items: []
      navbar_persistent: []
      footer_start: ["license"]
      footer_center: []
      footer_end: ["author"]
      show_prev_next: False
      navbar_align: right
      analytics:
        plausible_analytics_domain: dtcglaciers.org
        plausible_analytics_url: https://plausible.oggm.org/js/script.js
      icon_links:
        - name: GitHub
          url: https://github.com/DTC-Glaciers
          icon: "fa-brands fa-github"
          type: fontawesome
